import type { SwapListing } from "@/lib/matching/types";
import { formatCourseLabel } from "@/lib/universities/catalog";
import type { AcademicCourse, UniversityId } from "@/mock-data/types";
import { UNIVERSITIES } from "@/mock-data/universities";

/**
 * Resolves a course label from a university catalog.
 * @param universityId - School id
 * @param code - Course code
 * @returns Formatted label, or code when missing
 */
function course(universityId: UniversityId, code: string): string {
	const university = UNIVERSITIES.find((item) => item.id === universityId);
	if (!university) {
		return code;
	}

	for (const category of university.categories) {
		const match: AcademicCourse | undefined = category.courses.find((item) => item.code === code);
		if (match) {
			return formatCourseLabel(match);
		}
	}

	return code;
}

/**
 * Marketplace listings for general skill and school course matching.
 */
export const SWAP_LISTINGS: SwapListing[] = [
	// —— General perfect / partial fodder ——
	{
		id: "gen-victony",
		kind: "general",
		name: "Victony Darey",
		verified: true,
		rating: 4.8,
		ratingPercent: 63,
		teaches: ["Python", "JavaScript", "SQL"],
		wantsToLearn: ["UI design", "Figma"],
		listedAt: "2026-11-25T12:43:42.000Z",
	},
	{
		id: "gen-gideon-rate",
		kind: "general",
		name: "Gideon Jefferson",
		verified: true,
		rating: 4.9,
		ratingPercent: 71,
		teaches: ["Python", "Data analysis"],
		wantsToLearn: ["UI design", "Brand identity"],
		listedAt: "2026-11-24T09:12:08.000Z",
		rateAmountNgn: 2000,
		ratePeriod: "weekly",
	},
	{
		id: "gen-gideon-partial",
		kind: "general",
		name: "Gideon Jefferson",
		verified: true,
		rating: 4.6,
		ratingPercent: 58,
		teaches: ["TypeScript", "Web development"],
		wantsToLearn: ["Guitar", "Piano"],
		listedAt: "2026-11-20T16:05:21.000Z",
	},
	{
		id: "gen-onyekachi",
		kind: "general",
		name: "Onyekachi Nnaemena",
		verified: true,
		rating: 4.7,
		ratingPercent: 64,
		teaches: ["Figma", "UI design", "Graphic design"],
		wantsToLearn: ["Python", "JavaScript"],
		listedAt: "2026-11-18T08:22:10.000Z",
	},
	{
		id: "gen-adaobi",
		kind: "general",
		name: "Adaobi Okeke",
		verified: true,
		rating: 4.5,
		ratingPercent: 55,
		teaches: ["English", "French", "Public speaking"],
		wantsToLearn: ["Python", "SQL"],
		listedAt: "2026-11-15T14:01:44.000Z",
		rateAmountNgn: 3500,
		ratePeriod: "weekly",
	},
	{
		id: "gen-chinedu",
		kind: "general",
		name: "Chinedu Eze",
		verified: false,
		rating: 4.2,
		ratingPercent: 49,
		teaches: ["Barbing", "Cooking"],
		wantsToLearn: ["Mobile development", "JavaScript"],
		listedAt: "2026-11-12T11:33:02.000Z",
	},
	{
		id: "gen-funke",
		kind: "general",
		name: "Funke Adeyemi",
		verified: true,
		rating: 4.9,
		ratingPercent: 80,
		teaches: ["Portrait photography", "Photo editing", "Videography"],
		wantsToLearn: ["Brand identity", "Illustration"],
		listedAt: "2026-11-10T19:40:55.000Z",
	},
	{
		id: "gen-ibrahim",
		kind: "general",
		name: "Ibrahim Musa",
		verified: true,
		rating: 4.4,
		ratingPercent: 52,
		teaches: ["Hausa", "Personal finance", "Driving"],
		wantsToLearn: ["Web development", "SQL"],
		listedAt: "2026-11-08T07:18:29.000Z",
		rateAmountNgn: 1500,
		ratePeriod: "daily",
	},
	{
		id: "gen-ngozi",
		kind: "general",
		name: "Ngozi Umeh",
		verified: true,
		rating: 4.8,
		ratingPercent: 69,
		teaches: ["UX research", "Figma", "UI design"],
		wantsToLearn: ["TypeScript", "Go"],
		listedAt: "2026-11-05T13:27:16.000Z",
	},
	{
		id: "gen-tunde",
		kind: "general",
		name: "Tunde Bakare",
		verified: false,
		rating: 4.1,
		ratingPercent: 44,
		teaches: ["Guitar", "Vocals", "Music production"],
		wantsToLearn: ["Video editing", "Product photography"],
		listedAt: "2026-11-02T21:09:03.000Z",
	},
	{
		id: "gen-amaka",
		kind: "general",
		name: "Amaka Obi",
		verified: true,
		rating: 4.7,
		ratingPercent: 66,
		teaches: ["Java", "C++", "Data analysis"],
		wantsToLearn: ["Figma", "UI design"],
		listedAt: "2026-10-30T10:55:41.000Z",
		rateAmountNgn: 5000,
		ratePeriod: "monthly",
	},
	{
		id: "gen-kemi",
		kind: "general",
		name: "Kemi Balogun",
		verified: true,
		rating: 4.6,
		ratingPercent: 61,
		teaches: ["Yoruba", "Cooking", "Swimming"],
		wantsToLearn: ["Python", "Web development"],
		listedAt: "2026-10-28T15:14:37.000Z",
	},
	{
		id: "gen-samuel",
		kind: "general",
		name: "Samuel Okoro",
		verified: true,
		rating: 4.3,
		ratingPercent: 50,
		teaches: ["Mobile development", "JavaScript", "TypeScript"],
		wantsToLearn: [],
		listedAt: "2026-10-25T09:48:12.000Z",
		rateAmountNgn: 4000,
		ratePeriod: "weekly",
	},
	{
		id: "gen-blessing",
		kind: "general",
		name: "Blessing Etuk",
		verified: false,
		rating: 4.0,
		ratingPercent: 41,
		teaches: ["Illustration", "Graphic design"],
		wantsToLearn: ["Igbo", "English"],
		listedAt: "2026-10-22T18:02:58.000Z",
	},
	{
		id: "gen-david",
		kind: "general",
		name: "David Nwosu",
		verified: true,
		rating: 4.8,
		ratingPercent: 72,
		teaches: ["Go", "SQL", "Python"],
		wantsToLearn: ["UX research", "Public speaking"],
		listedAt: "2026-10-20T12:11:06.000Z",
	},

	// —— School listings (UNN) ——
	{
		id: "sch-unn-chioma",
		kind: "school",
		name: "Chioma Okeke",
		verified: true,
		rating: 4.8,
		ratingPercent: 67,
		teaches: [course("unn", "COS 101"), course("unn", "COS 102")],
		wantsToLearn: [course("unn", "MTH 111"), course("unn", "MTH 121")],
		listedAt: "2026-11-25T12:43:42.000Z",
		universityId: "unn",
		level: 100,
		openToOtherSchools: false,
	},
	{
		id: "sch-unn-ebuka",
		kind: "school",
		name: "Ebuka Nwankwo",
		verified: true,
		rating: 4.7,
		ratingPercent: 62,
		teaches: [course("unn", "MTH 111"), course("unn", "MTH 211")],
		wantsToLearn: [course("unn", "COS 101"), course("unn", "COS 201")],
		listedAt: "2026-11-22T08:30:15.000Z",
		universityId: "unn",
		level: 200,
		rateAmountNgn: 2000,
		ratePeriod: "weekly",
		openToOtherSchools: true,
	},
	{
		id: "sch-unn-ifa",
		kind: "school",
		name: "Ifunanya Eze",
		verified: true,
		rating: 4.5,
		ratingPercent: 57,
		teaches: [course("unn", "COS 301"), course("unn", "COS 341")],
		wantsToLearn: [course("unn", "STA 311"), course("unn", "MTH 311")],
		listedAt: "2026-11-19T17:22:40.000Z",
		universityId: "unn",
		level: 300,
		openToOtherSchools: false,
	},
	{
		id: "sch-unn-obi",
		kind: "school",
		name: "Obinna Uche",
		verified: false,
		rating: 4.2,
		ratingPercent: 48,
		teaches: [course("unn", "STA 111"), course("unn", "STA 211")],
		wantsToLearn: [course("unn", "COS 102"), course("unn", "COS 202")],
		listedAt: "2026-11-14T11:05:33.000Z",
		universityId: "unn",
		level: 200,
		openToOtherSchools: true,
	},

	// —— School listings (UNILAG) ——
	{
		id: "sch-unilag-tola",
		kind: "school",
		name: "Tola Adebayo",
		verified: true,
		rating: 4.9,
		ratingPercent: 74,
		teaches: [course("unilag", "CSC 111"), course("unilag", "CSC 120")],
		wantsToLearn: [course("unilag", "MTH 111"), course("unilag", "MTH 112")],
		listedAt: "2026-11-21T09:40:18.000Z",
		universityId: "unilag",
		level: 100,
		openToOtherSchools: false,
	},
	{
		id: "sch-unilag-seyi",
		kind: "school",
		name: "Seyi Ogunleye",
		verified: true,
		rating: 4.6,
		ratingPercent: 60,
		teaches: [course("unilag", "MTH 111"), course("unilag", "STA 111")],
		wantsToLearn: [course("unilag", "CSC 111"), course("unilag", "CSC 220")],
		listedAt: "2026-11-17T14:55:02.000Z",
		universityId: "unilag",
		level: 100,
		rateAmountNgn: 2500,
		ratePeriod: "weekly",
		openToOtherSchools: true,
	},
	{
		id: "sch-unilag-bimpe",
		kind: "school",
		name: "Bimpe Lawal",
		verified: true,
		rating: 4.4,
		ratingPercent: 53,
		teaches: [course("unilag", "CSC 220"), course("unilag", "CSC 314")],
		wantsToLearn: [course("unilag", "CSC 322"), course("unilag", "MTH 211")],
		listedAt: "2026-11-11T16:28:47.000Z",
		universityId: "unilag",
		level: 200,
		openToOtherSchools: false,
	},

	// —— School listings (UI) ——
	{
		id: "sch-ui-adeola",
		kind: "school",
		name: "Adeola Fashola",
		verified: true,
		rating: 4.7,
		ratingPercent: 65,
		teaches: [course("ui", "CSC 101"), course("ui", "CSC 102")],
		wantsToLearn: [course("ui", "MAT 111"), course("ui", "MAT 121")],
		listedAt: "2026-11-23T10:12:29.000Z",
		universityId: "ui",
		level: 100,
		openToOtherSchools: true,
	},
	{
		id: "sch-ui-kunle",
		kind: "school",
		name: "Kunle Akinwale",
		verified: false,
		rating: 4.3,
		ratingPercent: 51,
		teaches: [course("ui", "MAT 111"), course("ui", "STA 121")],
		wantsToLearn: [course("ui", "CSC 101"), course("ui", "CSC 201")],
		listedAt: "2026-11-09T13:44:01.000Z",
		universityId: "ui",
		level: 100,
		rateAmountNgn: 1800,
		ratePeriod: "daily",
		openToOtherSchools: false,
	},

	// —— School listings (IMT) ——
	{
		id: "sch-imt-nnenna",
		kind: "school",
		name: "Nnenna Okafor",
		verified: true,
		rating: 4.6,
		ratingPercent: 59,
		teaches: [course("imt", "COM 111"), course("imt", "COM 112")],
		wantsToLearn: [course("imt", "STA 111"), course("imt", "ACC 111")],
		listedAt: "2026-11-16T08:08:54.000Z",
		universityId: "imt",
		level: 100,
		openToOtherSchools: false,
	},
	{
		id: "sch-imt-uche",
		kind: "school",
		name: "Uche Nwosu",
		verified: true,
		rating: 4.5,
		ratingPercent: 56,
		teaches: [course("imt", "ACC 111"), course("imt", "ACC 211")],
		wantsToLearn: [course("imt", "COM 111"), course("imt", "COM 211")],
		listedAt: "2026-11-07T19:21:36.000Z",
		universityId: "imt",
		level: 200,
		rateAmountNgn: 1200,
		ratePeriod: "hour",
		openToOtherSchools: true,
	},

	// —— School listings (UNICAL / UNIZIK) ——
	{
		id: "sch-unical-esther",
		kind: "school",
		name: "Esther Bassey",
		verified: true,
		rating: 4.8,
		ratingPercent: 70,
		teaches: [course("unical", "CSC 111"), course("unical", "CSC 211")],
		wantsToLearn: [course("unical", "MTH 111"), course("unical", "STA 111")],
		listedAt: "2026-11-13T12:00:00.000Z",
		universityId: "unical",
		level: 200,
		openToOtherSchools: true,
	},
	{
		id: "sch-unizik-chidi",
		kind: "school",
		name: "Chidi Okonkwo",
		verified: true,
		rating: 4.4,
		ratingPercent: 54,
		teaches: [course("unizik", "CSC 101"), course("unizik", "CSC 102")],
		wantsToLearn: [course("unizik", "MTH 101"), course("unizik", "MTH 102")],
		listedAt: "2026-11-04T15:36:22.000Z",
		universityId: "unizik",
		level: 100,
		openToOtherSchools: false,
	},
	{
		id: "sch-unizik-ada",
		kind: "school",
		name: "Adaeze Nwosu",
		verified: false,
		rating: 4.1,
		ratingPercent: 46,
		teaches: [course("unizik", "MTH 101"), course("unizik", "STA 101")],
		wantsToLearn: [course("unizik", "CSC 101"), course("unizik", "CSC 201")],
		listedAt: "2026-10-29T07:45:19.000Z",
		universityId: "unizik",
		level: 100,
		rateAmountNgn: 2200,
		ratePeriod: "weekly",
		openToOtherSchools: true,
	},
];

/**
 * Listings for a given swap kind.
 * @param kind - general or school
 * @returns Filtered listings
 */
export function getListingsByKind(kind: SwapListing["kind"]): SwapListing[] {
	return SWAP_LISTINGS.filter((listing) => listing.kind === kind);
}
